import secrets
import requests

from odoo import api, fields, models
from odoo.exceptions import UserError


class MailGatewayAIIdentity(models.Model):
    """Links an Odoo user to a messaging channel identity."""

    _name = "mail.gateway.ai.identity"
    _description = "OdooPilot User Identity"

    user_id = fields.Many2one("res.users", string="Odoo User", required=True, ondelete="cascade")
    channel = fields.Selection(
        [("telegram", "Telegram"), ("whatsapp", "WhatsApp")],
        string="Channel",
        required=True,
    )
    chat_id = fields.Char(string="Chat ID", required=True)
    display_name_channel = fields.Char(string="Channel Display Name")
    active = fields.Boolean(default=True)
    linked_at = fields.Datetime(string="Linked At", readonly=True)

    _sql_constraints = [
        ("unique_channel_chat", "UNIQUE(channel, chat_id)", "This chat is already linked to a user."),
    ]

    @api.model
    def action_generate_link_url(self) -> dict:
        """Generate a one-time link URL and open it in a wizard."""
        service_url = (
            self.env["ir.config_parameter"].sudo().get_param("mail_gateway_ai.service_url", "")
        )
        if not service_url:
            raise UserError("OdooPilot service URL is not configured in Settings.")

        # The actual token is generated by the OdooPilot service; we redirect the user there
        link_url = f"{service_url.rstrip('/')}/link/initiate?odoo_user_id={self.env.user.id}"
        return {
            "type": "ir.actions.act_url",
            "url": link_url,
            "target": "new",
        }
